### ISSUE TITLE
Smart Mode

### ISSUE THREAD

**Issue by WesleyMcGinn** [Bionic-Bison-5535/FORTE#8]
The robot currently boots to raw mode.  At competitions, however, raw mode should only be used in case of an emergency (e.g. if limelight breaks or navx quits).  Smart mode will be used by default, making the job of the driver easy and the job of FORTE more fun.

### Smart mode should include:
 - [x] Headless mode for driving (up on controller means away from alliance wall, regardless of which direction the robot is facing)
 - [ ] Automatic yaw correction (robot maintains set angle and returns quickly if bumped) (Done in #12)
 - [ ] Quick, POV-based rotation (POV on controller can be used to instantly point in a direction) (Done in #12)
 - [ ] Automatic, camera-based aim and launch sequence (for scoring while zooming by speaker)
 - [x] Automatic intake control and note processing (Done in #9)
 - [ ] Knowledge of location on the field (useful for auto) (Issue #10)
 - [ ] Easy, 1-click amp scoring
